name: Check Nix builds

on:
  push:
    branches:
      - master
  pull_request: {}
  workflow_dispatch: {}
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Nix
        uses: cachix/install-nix-action@v18
      - uses: cachix/cachix-action@v11
        with:
          name: nixpkgs-ruby
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - uses: actions/checkout@v3
      - run: NIXPKGS_ALLOW_BROKEN=1 nix flake check --print-build-logs --keep-going --impure

