name: Update Ruby versions

on:
  schedule:
    - cron: "30 5 * * *"
  workflow_dispatch: {}
jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
          ref: master
    - uses: actions/setup-node@v3
      with:
        node-version: 16.x
        cache: 'npm'
        cache-dependency-path: updater/package-lock.json
    - run: npm ci
      working-directory: ./updater
    - run: node updater/index.js
      env:
        ROOT_DIR: versions
    - uses: stefanzweifel/git-auto-commit-action@v4.14.1
      with:
        commit_message: Update Ruby versions
        branch: master

