name: Update Ruby versions

on:
  schedule:
    - cron: "30 5 * * *"
  workflow_dispatch: {}
permissions:
  pull-requests: write
  contents: write
jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
          ref: master
    - name: Install Nix
      uses: cachix/install-nix-action@v18
    - run: nix run .#update
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
    - name: Create Pull Request
      id: create-pull-request
      uses: peter-evans/create-pull-request@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: Update Ruby versions
        title: Update Ruby versions
        delete-branch: true
        branch: update-ruby-versions
    - uses: peter-evans/enable-pull-request-automerge@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        pull-request-number: ${{ steps.create-pull-request.outputs.pull-request-number }}

