name: Update Ruby versions

on:
  schedule:
    - cron: "30 5 * * *"
  workflow_dispatch: {}
jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
          ref: master
    - name: Install Nix
      uses: cachix/install-nix-action@v18
    - run: nix run .#update
    - uses: stefanzweifel/git-auto-commit-action@v4.16.0
      with:
        commit_message: Update Ruby versions
        branch: master

